// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Data;

#nullable disable

namespace QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005020029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.DangKyHoc", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaLop");

                    b.ToTable("DangKyHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaHocVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("CapDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgoaiNgu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoBuoi")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LichHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKhaiGiang")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.DangKyHoc", b =>
                {
                    b.HasOne("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.HocVien", "HocVien")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.LopHoc", "LopHoc")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.HocVien", b =>
                {
                    b.HasOne("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HocVien")
                        .HasForeignKey("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.HocVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.LopHoc", b =>
                {
                    b.HasOne("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.HocVien", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.KhoaHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.LopHoc", b =>
                {
                    b.Navigation("DangKyHocs");
                });

            modelBuilder.Entity("QuanLyTrungTamNgoaiNgu_UNETI04_TI17A2HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("HocVien");
                });
#pragma warning restore 612, 618
        }
    }
}
